site_name: Mindmap Hub
copyright: "© 2024 by Nguyen Quang Huy. All rights reserved."
repo_url: https://github.com/patrick204nqh/mindmaps
repo_name: patrick204nqh/mindmaps
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  icon:
    logo: material/cloudsync
    repo: fontawesome/brands/github-alt

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.section
    - navigation.indexes
    # - navigation.expand
    # - navigation.footer
    # - header.autohide
    - toc.integrate
    # - tabs
    - content.code.copy
    - content.code.edit
    - content.code.view

plugins:
  - search
  - group:
      plugins:
        - search
        - blog
        - offline
        - social
        - tags
        - sitemap
        - redirect
  - git-revision-date-localized
  - git-authors
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: ''
      lib_version: ''
      view_version: ''

markdown_extensions:
  - toc:
      permalink: true      # Adds anchor links to headings for easier navigation
      toc_depth: 4         # Controls the depth of the table of contents
  - admonition             # Adds styled block notes (e.g., warning, note)
  - footnotes              # Enables inline footnotes for references and explanations
  - def_list               # Adds support for definition lists
  - pymdownx.highlight     # Provides syntax highlighting for code blocks
  - pymdownx.superfences   # Supports nested and fenced code blocks
  - pymdownx.details       # Creates collapsible content sections
  - pymdownx.tasklist      # Enables GitHub-style task lists (checkboxes)
  - pymdownx.smartsymbols  # Converts common symbols (e.g., arrows) automatically
  - pymdownx.tilde         # Adds support for strikethrough text (e.g., ~text~)
  - pymdownx.emoji         # Allows the use of GitHub-style emoji
  - pymdownx.keys          # Renders keyboard keys (e.g., `Ctrl+C`)
  - pymdownx.critic        # Adds support for CriticMarkup, used for tracking changes (e.g., insertions, deletions)
  - pymdownx.caret         # Highlights new text with an insertion caret (useful for marking changes)
  - pymdownx.mark          # Highlights text with a background color
  - abbr                   # Supports abbreviations (e.g., HTML for HyperText Markup Language)
  - attr_list              # Enables custom attributes (e.g., adding classes to blocks)
  - tables                 # Adds support for markdown tables
  - md_in_html             # Allows mixing markdown and HTML in the same document

extra:
  analytics:
    provider: google
    property: G-J1JYFW2Z1B
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: |
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: |
            Thanks for your feedback! Help us improve this page by using our 
            <a href="https://github.com/patrick204nqh/mindmaps/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patrick204nqh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/patrick204nqh
  generator: false

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/js/markmap-d3.js
  - assets/js/markmap-lib.js
  - assets/js/markmap-view.js

nav:
  - Home:
    - index.md

  # English Section
  - English:
    - english/index.md
    - Vocabulary:
      - english/vocabulary/index.md
      - A1 - Beginner: english/vocabulary/a1/index.md
      - A2 - Elementary: english/vocabulary/a2/index.md
      - B1 - Intermediate: english/vocabulary/b1/index.md
      - B2 - Upper-Intermediate: english/vocabulary/b2/index.md
      - C1 - Advanced: english/vocabulary/c1/index.md
      - C2 - Proficient: english/vocabulary/c2/index.md
    - Grammar:
      - english/grammar/index.md
      - A1 - Beginner: english/grammar/a1/index.md
      - A2 - Elementary: english/grammar/a2/index.md
      - B1 - Intermediate: english/grammar/b1/index.md
      - B2 - Upper-Intermediate: english/grammar/b2/index.md
      - C1 - Advanced: english/grammar/c1/index.md
      - C2 - Proficient: english/grammar/c2/index.md
      - Mindmaps: english/grammar/mindmaps/index.md
    - Idioms & Expressions:
      - english/idioms_expressions/index.md
    - Reading Practice:
      - english/reading_practice/index.md
    - Listening Practice:
      - english/listening_practice/index.md
    - Speaking Practice:
      - english/speaking_practice/index.md
    - Writing Skills:
      - english/writing_skills/index.md
    - Exam Preparation:
      - TOEIC: english/exam_preparation/toeic.md
      - IELTS: english/exam_preparation/ielts.md

  # Placeholder for Technical Section
  # - Technical:
  #   - Programming Languages:
  #     - Ruby: technical/programming_languages/ruby.md
  #     - Python: technical/programming_languages/python.md
  #     - JavaScript: technical/programming_languages/javascript.md
  #   - DevOps:
  #     - Docker: technical/devops/docker.md
  #     - Kubernetes: technical/devops/kubernetes.md
  #   - Backend:
  #     - REST APIs: technical/backend/rest_apis.md
  #     - GraphQL: technical/backend/graphql.md
  #   - Frontend:
  #     - React: technical/frontend/react.md
  #     - Vue.js: technical/frontend/vue.md
  #   - Databases:
  #     - PostgreSQL: technical/databases/postgresql.md