site_name: Mindmap Hub
copyright: "© 2024 by Nguyen Quang Huy. All rights reserved."
repo_url: https://github.com/patrick204nqh/mindmaps
repo_name: patrick204nqh/mindmaps

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/img/logo.svg
  favicon: assets/img/favicon.ico
  icon:
    logo: material/cloudsync
    repo: fontawesome/brands/github-alt

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.section
    - navigation.indexes
    # - navigation.expand
    # - navigation.footer
    # - header.autohide
    - toc.integrate
    # - tabs
    - content.code.copy
    - content.code.edit
    - content.code.view

plugins:
  - search
  - tags
  # - info
  # - typeset
  - group:
      enabled: true
      plugins:
        # - meta
        - social
        - privacy
        # - optimize
        # - offline
        - git-revision-date-localized
        - git-authors
        # - minify: 
        #     minify_html: true
        #     htmlmin_opts:
        #       remove_comments: true
        #     cache_safe: true
            # minify_js: true
            # minify_css: true
            # js_files:
              # - assets/js/markmap-d3.js
              # - assets/js/markmap-lib.js
              # - assets/js/markmap-view.js
            # css_files:
            #   - assets/css/extra.css
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      # start: <!--start-->
      # end: <!--end-->
      recursive: true
      # opening_tag: "{%"
      # closing_tag: "%}"
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: ''
      lib_version: ''
      view_version: ''
  - abs-to-rel

markdown_extensions:
  - toc:
      permalink: true      # Adds anchor links to headings for easier navigation
      toc_depth: 4         # Controls the depth of the table of contents
  - admonition             # Adds styled block notes (e.g., warning, note)
  - footnotes              # Enables inline footnotes for references and explanations
  - def_list               # Adds support for definition lists
  - pymdownx.highlight     # Provides syntax highlighting for code blocks
  - pymdownx.superfences   # Supports nested and fenced code blocks
  - pymdownx.details       # Creates collapsible content sections
  - pymdownx.tasklist      # Enables GitHub-style task lists (checkboxes)
  - pymdownx.smartsymbols  # Converts common symbols (e.g., arrows) automatically
  - pymdownx.tilde         # Adds support for strikethrough text (e.g., ~text~)
  - pymdownx.emoji         # Allows the use of GitHub-style emoji
  - pymdownx.keys          # Renders keyboard keys (e.g., `Ctrl+C`)
  - pymdownx.critic        # Adds support for CriticMarkup, used for tracking changes (e.g., insertions, deletions)
  - pymdownx.caret         # Highlights new text with an insertion caret (useful for marking changes)
  - pymdownx.mark          # Highlights text with a background color
  - abbr                   # Supports abbreviations (e.g., HTML for HyperText Markup Language)
  - attr_list              # Enables custom attributes (e.g., adding classes to blocks)
  - tables                 # Adds support for markdown tables
  - md_in_html             # Allows mixing markdown and HTML in the same document

extra:
  analytics:
    provider: google
    property: G-J1JYFW2Z1B
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: |
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: |
            Thanks for your feedback! Help us improve this page by using our 
            <a href="https://github.com/patrick204nqh/mindmaps/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patrick204nqh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/patrick204nqh
  generator: false

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/markmap-d3.js
  - assets/js/markmap-lib.js
  - assets/js/markmap-view.js

exclude_docs: |
  mkdocs.yml
  README.md
  markmap/**/*.mm.md

nav:
  - Home:
    - index.md
    - Overview: overview.md
    - About: about.md

  # English Section
  - English:
    - english/index.md
    - Vocabulary:
      - english/vocabulary/index.md
      - A1 - Beginner:
        - english/vocabulary/a1/index.md
        - Body & Health: english/vocabulary/a1/body_health.md
        - Clothes & Colors: english/vocabulary/a1/clothes_colors.md
        - Common Adjectives: english/vocabulary/a1/common_adjectives.md
        - Common Verbs & Actions: english/vocabulary/a1/common_verbs_actions.md
        - Common Places: english/vocabulary/a1/common_places.md
        - Feelings & Emotions: english/vocabulary/a1/feelings_emotions.md
        - Food & Drink: english/vocabulary/a1/food_drink.md
        - Hobbies & Leisure: english/vocabulary/a1/hobbies_leisure.md
        - Numbers & Quantities: english/vocabulary/a1/numbers_quantities.md
        - People & Family: english/vocabulary/a1/people_family.md
        - Prepositions: english/vocabulary/a1/prepositions.md
        - Pronouns & Possessives: english/vocabulary/a1/pronouns_possessives.md
        - Question Words: english/vocabulary/a1/question_words.md
        - Time & Dates: english/vocabulary/a1/time_dates.md
        - Transportation: english/vocabulary/a1/transportation.md
        - Weather & Seasons: english/vocabulary/a1/weather_seasons.md
        - Occupations: english/vocabulary/a1/occupations.md
      - A2 - Elementary:
        - english/vocabulary/a2/index.md
        # - Personal Information & Biographies: english/vocabulary/a2/personal_information.md
        # - Shopping & Money: english/vocabulary/a2/shopping_money.md
        # - Travel & Directions: english/vocabulary/a2/travel_directions.md
        # - Health & Fitness: english/vocabulary/a2/health_fitness.md
        # - Work & Jobs: english/vocabulary/a2/work_jobs.md
        # - Education & School: english/vocabulary/a2/education_school.md
        # - House & Home: english/vocabulary/a2/house_home.md
        # - Entertainment & Media: english/vocabulary/a2/entertainment_media.md
        # - Technology & Gadgets: english/vocabulary/a2/technology_gadgets.md
        # - Food & Cooking: english/vocabulary/a2/food_cooking.md
        # - Feelings & Opinions: english/vocabulary/a2/feelings_opinions.md
      - B1 - Intermediate:
        - english/vocabulary/b1/index.md
        # - Work & Employment: english/vocabulary/b1/work_employment.md
        # - Education & Learning: english/vocabulary/b1/education_learning.md
        # - Health & Medicine: english/vocabulary/b1/health_medicine.md
        # - Travel & Tourism: english/vocabulary/b1/travel_tourism.md
        # - Media & Communication: english/vocabulary/b1/media_communication.md
        # - Environment & Nature: english/vocabulary/b1/environment_nature.md
        # - Society & Culture: english/vocabulary/b1/society_culture.md
        # - Science & Technology: english/vocabulary/b1/science_technology.md
        # - Relationships & Emotions: english/vocabulary/b1/relationships_emotions.md
        # - Leisure Activities: english/vocabulary/b1/leisure_activities.md
      - B2 - Upper-Intermediate:
        - english/vocabulary/b2/index.md
        # - Current Events & News: english/vocabulary/b2/current_events_news.md
        # - Advanced Technology: english/vocabulary/b2/advanced_technology.md
        # - Media & Entertainment: english/vocabulary/b2/media_entertainment.md
        # - Global Issues & Environment: english/vocabulary/b2/global_issues_environment.md
        # - Business & Finance: english/vocabulary/b2/business_finance.md
        # - Art & Literature: english/vocabulary/b2/art_literature.md
        # - Philosophy & Ethics: english/vocabulary/b2/philosophy_ethics.md
        # - Law & Government: english/vocabulary/b2/law_government.md
        # - Advanced Education: english/vocabulary/b2/advanced_education.md
      - C1 - Advanced:
        - english/vocabulary/c1/index.md
        # - Advanced Business Concepts: english/vocabulary/c1/advanced_business_concepts.md
        # - Legal Terminology: english/vocabulary/c1/legal_terminology.md
        # - Political Science: english/vocabulary/c1/political_science.md
        # - Cultural Studies: english/vocabulary/c1/cultural_studies.md
        # - Advanced Science & Technology: english/vocabulary/c1/advanced_science_technology.md
        # - Psychology & Sociology: english/vocabulary/c1/psychology_sociology.md
        # - Academic Writing & Research: english/vocabulary/c1/academic_writing_research.md
        # - Idioms & Expressions: english/vocabulary/c1/idioms_expressions.md
        # - Philosophy & Ethics: english/vocabulary/c1/philosophy_ethics.md
      - C2 - Proficient:
        - english/vocabulary/c2/index.md
        # - Academic Research & Analysis: english/vocabulary/c2/academic_research_analysis.md
        # - Advanced Literary Terms: english/vocabulary/c2/advanced_literary_terms.md
        # - Technical & Scientific Vocabulary: english/vocabulary/c2/technical_scientific_vocabulary.md
        # - Advanced Idiomatic Expressions: english/vocabulary/c2/advanced_idiomatic_expressions.md
        # - Cross-Cultural Communication: english/vocabulary/c2/cross_cultural_communication.md
        # - Advanced Philosophy & Theory: english/vocabulary/c2/advanced_philosophy_theory.md
        # - Professional & Legal Jargon: english/vocabulary/c2/professional_legal_jargon.md
        # - Business & Economics: english/vocabulary/c2/business_economics.md
        # - Medical Terminology: english/vocabulary/c2/medical_terminology.md
    - Grammar:
      - english/grammar/index.md
      - A1 - Beginner:
        - english/grammar/a1/index.md
      - A2 - Elementary:
        - english/grammar/a2/index.md
      - B1 - Intermediate:
        - english/grammar/b1/index.md
      - B2 - Upper-Intermediate:
        - english/grammar/b2/index.md
      - C1 - Advanced:
        - english/grammar/c1/index.md
      - C2 - Proficient:
        - english/grammar/c2/index.md
      - Mindmaps:
        - english/grammar/mindmaps/index.md
    - Idioms & Expressions:
      - english/idioms_expressions/index.md
    - Reading Practice:
      - english/reading_practice/index.md
    - Listening Practice:
      - english/listening_practice/index.md
    - Speaking Practice:
      - english/speaking_practice/index.md
    - Writing Skills:
      - english/writing_skills/index.md
    - Exam Preparation:
      - TOEIC: english/exam_preparation/toeic.md
      - IELTS: english/exam_preparation/ielts.md

  # Placeholder for Technical Section
  # - Technical:
  #   - Programming Languages:
  #     - Ruby: technical/programming_languages/ruby.md
  #     - Python: technical/programming_languages/python.md
  #     - JavaScript: technical/programming_languages/javascript.md
  #   - DevOps:
  #     - Docker: technical/devops/docker.md
  #     - Kubernetes: technical/devops/kubernetes.md
  #   - Backend:
  #     - REST APIs: technical/backend/rest_apis.md
  #     - GraphQL: technical/backend/graphql.md
  #   - Frontend:
  #     - React: technical/frontend/react.md
  #     - Vue.js: technical/frontend/vue.md
  #   - Databases:
  #     - PostgreSQL: technical/databases/postgresql.md