site_name: Mindmap Hub
site_url: https://patrick204nqh.github.io/mindmaps/
copyright: "© 2024 by Nguyen Quang Huy. All rights reserved."
repo_url: https://github.com/patrick204nqh/mindmaps
repo_name: patrick204nqh/mindmaps

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/img/logo.svg
  favicon: assets/img/favicon.ico
  icon:
    logo: material/cloudsync
    repo: fontawesome/brands/github-alt
  custom_dir: overrides

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.section
    - navigation.indexes
    # - navigation.expand
    # - navigation.footer
    # - header.autohide
    - toc.integrate
    # - tabs
    - content.code.copy
    - content.code.edit
    - content.code.view

plugins:
  - search
  - macros
  - tags
  # - info
  # - typeset
  - group:
      enabled: true
      plugins:
        # - meta
        - social
        - privacy
        # - optimize
        # - offline
        - git-revision-date-localized
        - git-authors
        # - minify: 
        #     minify_html: true
        #     htmlmin_opts:
        #       remove_comments: true
        #     cache_safe: true
            # minify_js: true
            # minify_css: true
            # js_files:
              # - assets/js/markmap-d3.js
              # - assets/js/markmap-lib.js
              # - assets/js/markmap-view.js
            # css_files:
            #   - assets/css/extra.css
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      # start: <!--start-->
      # end: <!--end-->
      recursive: true
      # opening_tag: "{%"
      # closing_tag: "%}"
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: '' # '7.9.0'
      lib_version: '' # '0.17.3-alpha.2'
      view_version: '' # '0.17.3-alpha.1'
  - abs-to-rel

markdown_extensions:
  - toc:
      permalink: true      # Adds anchor links to headings for easier navigation
      toc_depth: 4         # Controls the depth of the table of contents
  - admonition             # Adds styled block notes (e.g., warning, note)
  - footnotes              # Enables inline footnotes for references and explanations
  - def_list               # Adds support for definition lists
  - pymdownx.highlight     # Provides syntax highlighting for code blocks
  - pymdownx.superfences   # Supports nested and fenced code blocks
  - pymdownx.details       # Creates collapsible content sections
  - pymdownx.tasklist      # Enables GitHub-style task lists (checkboxes)
  - pymdownx.smartsymbols  # Converts common symbols (e.g., arrows) automatically
  - pymdownx.tilde         # Adds support for strikethrough text (e.g., ~text~)
  - pymdownx.emoji         # Allows the use of GitHub-style emoji
  - pymdownx.keys          # Renders keyboard keys (e.g., `Ctrl+C`)
  - pymdownx.critic        # Adds support for CriticMarkup, used for tracking changes (e.g., insertions, deletions)
  - pymdownx.caret         # Highlights new text with an insertion caret (useful for marking changes)
  - pymdownx.mark          # Highlights text with a background color
  - pymdownx.tasklist      # Enables GitHub-style task lists (checkboxes)
  - abbr                   # Supports abbreviations (e.g., HTML for HyperText Markup Language)
  - attr_list              # Enables custom attributes (e.g., adding classes to blocks)
  - tables                 # Adds support for markdown tables
  - md_in_html             # Allows mixing markdown and HTML in the same document
  - mdx_truly_sane_lists   # Fixes nested lists in markdown

extra:
  analytics:
    provider: google
    property: G-J1JYFW2Z1B
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: |
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: |
            Thanks for your feedback! Help us improve this page by using our 
            <a href="https://github.com/patrick204nqh/mindmaps/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patrick204nqh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/patrick204nqh
  generator: false

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/mkdocs-markmap/markmap-d3.js
  - assets/js/mkdocs-markmap/markmap-lib.js
  - assets/js/mkdocs-markmap/markmap-view.js

exclude_docs: |
  mkdocs.yml
  README.md
  markmap/**/*.mm.md

nav:
  - Home:
    - index.md
    - Overview: overview.md
    - About: about.md

  # English Section
  - English:
    - english/index.md
    - Vocabulary:
      - english/vocabulary/index.md
      - A1 - Beginner:
        - english/vocabulary/a1/index.md
        - Body & Health: english/vocabulary/a1/body_health.md
        - Clothes & Colors: english/vocabulary/a1/clothes_colors.md
        - Common Adjectives: english/vocabulary/a1/common_adjectives.md
        - Common Verbs & Actions: english/vocabulary/a1/common_verbs_actions.md
        - Common Places: english/vocabulary/a1/common_places.md
        - Feelings & Emotions: english/vocabulary/a1/feelings_emotions.md
        - Food & Drink: english/vocabulary/a1/food_drink.md
        - Hobbies & Free Time: english/vocabulary/a1/hobbies_free_time.md
        - Numbers & Quantities: english/vocabulary/a1/numbers_quantities.md
        - People & Family: english/vocabulary/a1/people_family.md
        - Prepositions: english/vocabulary/a1/prepositions.md
        - Pronouns & Possessives: english/vocabulary/a1/pronouns_possessives.md
        - Question Words: english/vocabulary/a1/question_words.md
        - Time & Dates: english/vocabulary/a1/time_dates.md
        - Transportation: english/vocabulary/a1/transportation.md
        - Weather & Seasons: english/vocabulary/a1/weather_seasons.md
        - Occupations: english/vocabulary/a1/occupations.md
        - Wrapped: english/vocabulary/a1/_wrapped.md
      - A2 - Elementary:
        - english/vocabulary/a2/index.md
        - Personal Information & Biographies: english/vocabulary/a2/personal_information.md
        - Shopping & Money: english/vocabulary/a2/shopping_money.md
        - Travel & Directions: english/vocabulary/a2/travel_directions.md
        - Health & Fitness: english/vocabulary/a2/health_fitness.md
        - Work & Jobs: english/vocabulary/a2/work_jobs.md
        - Education & School: english/vocabulary/a2/education_school.md
        - House & Home: english/vocabulary/a2/house_home.md
        - Entertainment & Media: english/vocabulary/a2/entertainment_media.md
        - Technology & Gadgets: english/vocabulary/a2/technology_gadgets.md
        - Food & Cooking: english/vocabulary/a2/food_cooking.md
        - Feelings & Opinions: english/vocabulary/a2/feelings_opinions.md
        - Wrapped: english/vocabulary/a2/_wrapped.md
      - B1 - Intermediate:
        - english/vocabulary/b1/index.md
        - Work & Employment: english/vocabulary/b1/work_employment.md
        - Education & Learning: english/vocabulary/b1/education_learning.md
        - Health & Medicine: english/vocabulary/b1/health_medicine.md
        - Travel & Tourism: english/vocabulary/b1/travel_tourism.md
        - Media & Communication: english/vocabulary/b1/media_communication.md
        - Environment & Nature: english/vocabulary/b1/environment_nature.md
        - Society & Culture: english/vocabulary/b1/society_culture.md
        - Science & Technology: english/vocabulary/b1/science_technology.md
        - Relationships & Emotions: english/vocabulary/b1/relationships_emotions.md
        - Leisure Activities: english/vocabulary/b1/leisure_activities.md
        - Wrapped: english/vocabulary/b1/_wrapped.md
      - B2 - Upper-Intermediate:
        - english/vocabulary/b2/index.md
        - Current Events & News: english/vocabulary/b2/current_events_news.md
        - Advanced Technology: english/vocabulary/b2/advanced_technology.md
        - Media & Entertainment: english/vocabulary/b2/media_entertainment.md
        - Global Issues & Environment: english/vocabulary/b2/global_issues_environment.md
        - Business & Finance: english/vocabulary/b2/business_finance.md
        - Art & Literature: english/vocabulary/b2/art_literature.md
        - Philosophy & Ethics: english/vocabulary/b2/philosophy_ethics.md
        - Law & Government: english/vocabulary/b2/law_government.md
        - Advanced Education: english/vocabulary/b2/advanced_education.md
        - Wrapped: english/vocabulary/b2/_wrapped.md
      - C1 - Advanced:
        - english/vocabulary/c1/index.md
        - Advanced Business Concepts: english/vocabulary/c1/advanced_business_concepts.md
        - Legal Terminology: english/vocabulary/c1/legal_terminology.md
        - Political Science: english/vocabulary/c1/political_science.md
        - Cultural Studies: english/vocabulary/c1/cultural_studies.md
        - Advanced Science & Technology: english/vocabulary/c1/advanced_science_technology.md
        - Psychology & Sociology: english/vocabulary/c1/psychology_sociology.md
        - Academic Writing & Research: english/vocabulary/c1/academic_writing_research.md
        - Idioms & Expressions: english/vocabulary/c1/idioms_expressions.md
        - Philosophy & Ethics: english/vocabulary/c1/philosophy_ethics.md
      - C2 - Proficient:
        - english/vocabulary/c2/index.md
        - Academic Research & Analysis: english/vocabulary/c2/academic_research_analysis.md
        - Advanced Literary Terms: english/vocabulary/c2/advanced_literary_terms.md
        - Technical & Scientific Vocabulary: english/vocabulary/c2/technical_scientific_vocabulary.md
        - Advanced Idiomatic Expressions: english/vocabulary/c2/advanced_idiomatic_expressions.md
        - Cross-Cultural Communication: english/vocabulary/c2/cross_cultural_communication.md
        - Advanced Philosophy & Theory: english/vocabulary/c2/advanced_philosophy_theory.md
        - Professional & Legal Jargon: english/vocabulary/c2/professional_legal_jargon.md
        - Business & Economics: english/vocabulary/c2/business_economics.md
        - Medical Terminology: english/vocabulary/c2/medical_terminology.md
      - Wrapped: english/vocabulary/_wrapped.md
    - Grammar:
      - english/grammar/index.md
      - A1 - Beginner:
        - english/grammar/a1/index.md
        - Nouns: english/grammar/a1/nouns.md
        - Articles (a, an, the): english/grammar/a1/articles.md
        - Pronouns: english/grammar/a1/pronouns.md
        - Possessive Adjectives (my, your, his, her): english/grammar/a1/possessive_adjectives.md
        - Demonstratives (this, that, these, those): english/grammar/a1/demonstratives.md
        - Present Simple: english/grammar/a1/present_simple.md
        - Imperatives: english/grammar/a1/imperatives.md
        - Basic Sentence Structure: english/grammar/a1/basic_sentence_structure.md
        - Adjectives: english/grammar/a1/adjectives.md
        - Prepositions of Place: english/grammar/a1/prepositions_of_place.md
        - Conjunctions (and, but, or): english/grammar/a1/conjunctions.md
        - Question Words: english/grammar/a1/question_words.md
        - Modal Verbs (can for ability): english/grammar/a1/modal_can.md
        - Adverbs of Frequency (always, never): english/grammar/a1/adverbs_of_frequency.md
        - Wrapped: english/grammar/a1/_wrapped.md
      - A2 - Elementary:
        - english/grammar/a2/index.md
        - Present Continuous: english/grammar/a2/present_continuous.md
        - Past Simple: english/grammar/a2/past_simple.md
        - Future with "going to": english/grammar/a2/future_going_to.md
        - Future Simple ("will"): english/grammar/a2/future_simple.md
        - Comparatives & Superlatives: english/grammar/a2/comparatives_superlatives.md
        - Adverbs of Frequency: english/grammar/a2/adverbs_of_frequency.md
        - Modal Verbs (can, could, should, must): english/grammar/a2/modal_verbs.md
        - Prepositions of Time and Movement: english/grammar/a2/prepositions_time_movement.md
        - Possessive Pronouns (mine, yours, ours): english/grammar/a2/possessive_pronouns.md
        - There is / There are: english/grammar/a2/there_is_there_are.md
        - Countable and Uncountable Nouns: english/grammar/a2/countable_uncountable_nouns.md
        - Stative Verbs: english/grammar/a2/stative_verbs.md
        - Conjunctions (because, so): english/grammar/a2/conjunctions.md
        - Question Tags: english/grammar/a2/question_tags.md
        - Wrapped: english/grammar/a2/_wrapped.md
      - B1 - Intermediate:
        - english/grammar/b1/index.md
        - Present Perfect: english/grammar/b1/present_perfect.md
        - Past Continuous: english/grammar/b1/past_continuous.md
        - Future Forms (will, going to, Present Continuous): english/grammar/b1/future_forms.md
        - First Conditional: english/grammar/b1/first_conditional.md
        - Second Conditional: english/grammar/b1/second_conditional.md
        - Modal Verbs (must, have to, might, may): english/grammar/b1/modal_verbs.md
        - Relative Clauses: english/grammar/b1/relative_clauses.md
        - Reported Speech (Statements and Questions): english/grammar/b1/reported_speech.md
        - Gerunds and Infinitives: english/grammar/b1/gerunds_infinitives.md
        - Quantifiers (some, any, much, many): english/grammar/b1/quantifiers.md
        - Phrasal Verbs (Basic): english/grammar/b1/phrasal_verbs.md
        - Articles (Definite and Indefinite): english/grammar/b1/articles.md
        - Used to: english/grammar/b1/used_to.md
        - Wrapped: english/grammar/b1/_wrapped.md
      - B2 - Upper-Intermediate:
        - english/grammar/b2/index.md
        - Passive Voice: english/grammar/b2/passive_voice.md
        - Third Conditional: english/grammar/b2/third_conditional.md
        - Mixed Conditionals: english/grammar/b2/mixed_conditionals.md
        - Past Perfect: english/grammar/b2/past_perfect.md
        - Reported Speech (Advanced): english/grammar/b2/reported_speech.md
        - Phrasal Verbs (Advanced): english/grammar/b2/phrasal_verbs.md
        - Modal Verbs (should have, could have, needn't have): english/grammar/b2/modal_verbs.md
        - Relative Clauses (Advanced): english/grammar/b2/relative_clauses.md
        - Conditionals (Zero to Third): english/grammar/b2/conditionals.md
        - Wish / If Only: english/grammar/b2/wish_if_only.md
        - Linking Words and Phrases: english/grammar/b2/linking_words.md
        - Emphatic Structures: english/grammar/b2/emphatic_structures.md
        - Gerunds and Infinitives (Advanced): english/grammar/b2/gerunds_infinitives.md
        - Wrapped: english/grammar/b2/_wrapped.md
      - C1 - Advanced:
        - english/grammar/c1/index.md
        - Inversion: english/grammar/c1/inversion.md
        - Advanced Passive Structures: english/grammar/c1/advanced_passive.md
        - Cleft Sentences: english/grammar/c1/cleft_sentences.md
        - Nominalization: english/grammar/c1/nominalization.md
        - Ellipsis & Substitution: english/grammar/c1/ellipsis_substitution.md
        - Modal Verbs (Advanced Uses): english/grammar/c1/modal_verbs.md
        - Reported Speech (Complex): english/grammar/c1/reported_speech.md
        - Phrasal Verbs (Proficiency): english/grammar/c1/phrasal_verbs.md
        - Discourse Markers: english/grammar/c1/discourse_markers.md
        - Emphatic Inversion: english/grammar/c1/emphatic_inversion.md
        - Had Better, Would Rather: english/grammar/c1/had_better_would_rather.md
        - Wrapped: english/grammar/c1/_wrapped.md
      - C2 - Proficient:
        - english/grammar/c2/index.md
        - Subjunctive Mood: english/grammar/c2/subjunctive_mood.md
        - Advanced Conditionals: english/grammar/c2/advanced_conditionals.md
        - Cleft Sentences (Advanced): english/grammar/c2/cleft_sentences.md
        - Phrasal Verbs (Expert Level): english/grammar/c2/phrasal_verbs.md
        - Advanced Idiomatic Expressions: english/grammar/c2/idiomatic_expressions.md
        - Advanced Grammar Structures: english/grammar/c2/advanced_structures.md
        - Academic Writing Techniques: english/grammar/c2/academic_writing.md
        - Stylistic Inversions: english/grammar/c2/stylistic_inversions.md
        - Nuances in Modality: english/grammar/c2/nuances_modality.md
        - Advanced Punctuation: english/grammar/c2/advanced_punctuation.md
        - Complex Clause Structures: english/grammar/c2/complex_clauses.md
        - Discourse Markers (Advanced): english/grammar/c2/discourse_markers.md
        - Wrapped: english/grammar/c2/_wrapped.md
      - Summary:
        - english/grammar/summary/index.md
      - Wrapped: english/grammar/_wrapped.md
    - Idioms & Expressions:
      - english/idioms_expressions/index.md
    - Reading Practice:
      - english/reading_practice/index.md
    - Listening Practice:
      - english/listening_practice/index.md
    - Speaking Practice:
      - english/speaking_practice/index.md
    - Writing Skills:
      - english/writing_skills/index.md
    - Exam Preparation:
      - TOEIC: english/exam_preparation/toeic.md
      - IELTS: english/exam_preparation/ielts.md

  # Placeholder for Technical Section
  # - Technical:
  #   - Programming Languages:
  #     - Ruby: technical/programming_languages/ruby.md
  #     - Python: technical/programming_languages/python.md
  #     - JavaScript: technical/programming_languages/javascript.md
  #   - DevOps:
  #     - Docker: technical/devops/docker.md
  #     - Kubernetes: technical/devops/kubernetes.md
  #   - Backend:
  #     - REST APIs: technical/backend/rest_apis.md
  #     - GraphQL: technical/backend/graphql.md
  #   - Frontend:
  #     - React: technical/frontend/react.md
  #     - Vue.js: technical/frontend/vue.md
  #   - Databases:
  #     - PostgreSQL: technical/databases/postgresql.md