site_name: Mindmap Hub
copyright: "© 2024 by Nguyen Quang Huy. All rights reserved."
repo_url: https://github.com/patrick204nqh/mindmaps
repo_name: patrick204nqh/mindmaps
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom

  font:
    text: Roboto
    code: Roboto Mono

  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  icon:
    logo: material/cloudsync
    repo: fontawesome/brands/github-alt

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.section
    - navigation.indexes
    # - navigation.expand
    # - navigation.footer
    # - header.autohide
    - toc.integrate
    # - tabs
    - content.code.copy
    - content.code.edit
    - content.code.view

plugins:
  - search
  - group:
      plugins:
        - search
        - blog
        - offline
        - social
        - tags
        - sitemap
        - redirect
  - git-revision-date-localized
  - git-authors
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      # d3_version: '7'
      # lib_version: '0.15.3'
      # view_version: '0.15.3'

nav:
  - Home:
    - index.md

  # English Section
  - English:
    - Vocabulary:
      - english/vocabulary/index.md
      - General: english/vocabulary/general.md
      - Technical: english/vocabulary/technical.md
      - Phrasal Verbs: english/vocabulary/phrasal_verbs.md
      - Collocations: english/vocabulary/collocations.md
    - Grammar:
      - english/grammar/index.md
      - Tenses: english/grammar/tenses.md
      - Conditionals: english/grammar/conditionals.md
      - Modals: english/grammar/modals.md
      - Articles: english/grammar/articles.md
      - Sentence Structure: english/grammar/sentence_structure.md
      - Passive Voice: english/grammar/passive_voice.md
      - Prepositions: english/grammar/prepositions.md
      - Conjunctions: english/grammar/conjunctions.md      
    - Idioms & Expressions:
      - english/idioms_expressions/index.md
    - Reading Practice:
      - Short Stories: english/reading_practice/short_stories.md
      - News Articles: english/reading_practice/news_articles.md
      - Academic Texts: english/reading_practice/academic_texts.md
    - Listening Practice:
      - Podcasts: english/listening_practice/podcasts.md
      - TED Talks: english/listening_practice/ted_talks.md
      - Songs: english/listening_practice/songs.md
    - Speaking Practice:
      - Role Plays: english/speaking_practice/role_plays.md
      - Conversations: english/speaking_practice/conversations.md
      - Interviews: english/speaking_practice/interviews.md
    - Writing Skills:
      - Essays: english/writing_skills/essays.md
      - Emails: english/writing_skills/emails.md
      - Creative Writing: english/writing_skills/creative_writing.md
    - Exam Preparation:
      - TOEIC: english/exam_preparation/toeic.md
      - IELTS: english/exam_preparation/ielts.md

  # Placeholder for Technical Section
  # - Technical:
  #   - Programming Languages:
  #     - Ruby: technical/programming_languages/ruby.md
  #     - Python: technical/programming_languages/python.md
  #     - JavaScript: technical/programming_languages/javascript.md
  #   - DevOps:
  #     - Docker: technical/devops/docker.md
  #     - Kubernetes: technical/devops/kubernetes.md
  #   - Backend:
  #     - REST APIs: technical/backend/rest_apis.md
  #     - GraphQL: technical/backend/graphql.md
  #   - Frontend:
  #     - React: technical/frontend/react.md
  #     - Vue.js: technical/frontend/vue.md
  #   - Databases:
  #     - PostgreSQL: technical/databases/postgresql.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - admonition
  - footnotes
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/patrick204nqh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/patrick204nqh
  generator: false

extra_css:
  - assets/stylesheets/extra.css
