# settings.yaml
markmap:
  colorFreezeLevel: -1
  duration: 500
  maxWidth: 0
  initialExpandLevel: 5
  extraJs: []
  extraCss: []
  zoom: true
  pan: true

formatting:
  indent_size: 2
  line_spacing: 1