markmap:
  colorFreezeLevel: -1
  duration: 500
  maxWidth: 600
  initialExpandLevel: 3
  extraJs: []
  extraCss: []
  zoom: true
  pan: true
  spacingHorizontal: 80
  spacingVertical: 15

formatting:
  indent_size: 2
  line_spacing: 1

output:
  output_file_name: ".wrapped.mm.md"